const text1 = document.getElementById("text1");
const text2 = document.getElementById("text2");
const text3 = document.getElementById("text3");
const label4 = document.getElementById("label4");
const submit = document.getElementById("submit");
const reset = document.getElementById("reset");

submit.onclick = function () {
    let x, y, z, firstNum, lastNum, dateNum;

    let first = [];
    let last = [];
    let date = [];
    let pass = ["!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "_", "+",
        "-", "=", "{", "}", "[", "]", ":", ";", "\"", "'", "<", ">",
        ",", ".", "?", "/", "\\", "|", "~", "`"];
    let ran = [];
    let res = [];
    let iStr, iRan = 0;

    x = text1.value;
    y = text2.value;
    z = text3.value;

    if (/\d/.test(x) || /\d/.test(y)) {
        label4.textContent = `Name Should Contain Number`;
        return;
    }

    z = z.replaceAll("-", "");

    firstNum = x.length;
    lastNum = y.length;
    dateNum = z.length;

    firstNum = Number(firstNum);
    lastNum = Number(lastNum);
    dateNum = Number(dateNum);

    for (let i = 0; i < 3; i++) {
        first.push(x.charAt(i));
    }

    for (let i = lastNum / 2; i < lastNum; i++) {
        last.push(y.charAt(i));
    }
    for (let i = dateNum; i >= 0; i--) {
        if (i == 0) {
            date.push(z.charAt(i));
        }
        else if (i % 2 != 0) {
            date.push(z.charAt(i));
        }
    }

    let str = first.join('') + last.join('') + date.join('');
    str = str.trim();
    let a = str.length;
    a = Number(a);

    for (let i = 0; i < (a) && 30; i++) {
        let j = Math.floor(Math.random() * (firstNum + dateNum + lastNum)) + 1;
        j = Number(j);
        ran.push(pass[i]);

    }

    for (let i = 0; i < str.length; i++) {
        if (i % 2 == 0) {
            res.push(ran[i]);
        }
        if (i % 2 != 0) {
            res.push(str.charAt(i));
        }
    }

    label4.innerHTML = `Password Generated by given detail is : <b>${res.join('')}</b>`;
}

reset.onclick = function () {
    text1.value = ``;
    text2.value = ``;
    text3.value = ``;
    label4.textContent = ` `;
}